server:
  port: ${PORT:8083} # Indicate the default PORT where this service will be started
 
eureka:
  instance:
    hostname: 192.168.43.45
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
    maxThreadsForPeerReplication: 0